-- agegroup alanini 20-35 36-45 46-55 55-65 ve 65+ yas olarak guncelle

select*,
DATEDIFF(YEAR,BIRTHDATE,GETDATE()) AS AGE,
CASE
 WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 20 AND 35 THEN '20-35 YAS ARASI'
 WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 36 AND 45 THEN '36-45 YAS ARASI'
 WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 46 AND 55 THEN '46-55 YAS ARASI'
 WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 56 AND 65 THEN '5-65 YAS ARASI'
 WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) >65 THEN '65 YAS USTU'
END AGEGROUP2
from customers